# -*- coding: utf-8 -*-
"""Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F5xZwvlmMo5k0NXHj-C8bhpeySKL3X78

# **Code for Preprocessing the Binary Outlier Maps to convert them into Multi-class Segmentation Maps (Ground Truth)**

**Mounting Google Drive**
"""

from google.colab import drive
drive.mount('/content/drive')

"""**Mophological Operations and Geometric Corrections**"""

import os
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
from scipy.interpolate import make_interp_spline
from scipy.ndimage import binary_dilation, binary_erosion

#Defining directories
base_dir = '/content/drive/MyDrive/Thesis/Data/'
samples = [
    ('A-09_1_layer', 'Opening', (1, 10), (2, 20)),
    ('A-09_2_layer', 'Closing', (1, 40), (2, 40)),
    ('A-09_3_layer', 'Closing', (1, 40), (2, 40)),
    ('T-16_1_layer', 'Opening', (1, 10), (2, 20)),
    ('T-16_2_layer', 'Opening', (1, 10), (2, 20)),
    ('T-16_3_layer', 'Closing', (1, 40), (2, 40)),
    ('X5Y4_1_layer', 'Opening', (1, 10), (2, 20)),
    ('X5Y4_2_layer', 'Opening', (1, 10), (2, 20)),
    ('X5Y4_3_layer', 'Opening', (1, 5), (2, 5))
]

#Directories for saving results
output_txt_dir = '/content/drive/MyDrive/Thesis/Data/Multimasks_corrected_txt'
output_img_dir = '/content/drive/MyDrive/Thesis/Data/Multimasks_corrected'

#Creating output directories
os.makedirs(output_txt_dir, exist_ok=True)
os.makedirs(output_img_dir, exist_ok=True)

#Function for neighborhood label voting
def assign_label(neighborhood):
    center = neighborhood[4]
    if center != 0:
        return center
    window = np.delete(neighborhood, 4)
    count1 = np.sum(window == 1)
    count2 = np.sum(window == 2)
    return 1 if count1 >= count2 else 2

#Processing each sample
for sample_name, morph_op, param1, param2 in samples:
    print(f"Processing {sample_name} with {morph_op} operation and params {param1}, {param2}...")

    #Defining directories for the sample
    txt_dir = os.path.join(base_dir, sample_name, 'txt_binary')
    mask_dir = os.path.join(base_dir, sample_name, 'Masks')

    #Processing each binary mask .txt file
    for filename in sorted(os.listdir(txt_dir)):
        if not filename.endswith('.txt'):
            continue

        base_name = os.path.splitext(filename)[0]
        txt_path = os.path.join(txt_dir, filename)
        img_path = os.path.join(mask_dir, base_name + '.png')

        if not os.path.exists(img_path):
            print(f"Skipping {filename} — image not found")
            continue

        #Loading binary red mask and grayscale image
        red_mask = np.loadtxt(txt_path, dtype=np.uint8)
        base_image = np.array(Image.open(img_path).convert('L'))

        #Creating edge region mask (blue_mask)
        quarter_height = 3 * red_mask.shape[0] // 4
        upper = red_mask[:quarter_height, :].copy()

        #Applying the morphological operation (Opening or Closing)
        if morph_op == 'Opening':
            dilated = binary_dilation(upper, structure=np.ones(param1))
            closed = binary_erosion(dilated, structure=np.ones(param2))
        elif morph_op == 'Closing':
            dilated = binary_dilation(upper, structure=np.ones(param2))
            closed = binary_erosion(dilated, structure=np.ones(param1))

        #Applying spline interpolation to fill gaps
        for col in np.where(np.sum(closed, axis=0) == 0)[0]:
            left = col - 1
            right = col + 1
            while left >= 0 and np.sum(closed[:, left]) == 0: left -= 1
            while right < closed.shape[1] and np.sum(closed[:, right]) == 0: right += 1
            if left >= 0 and right < closed.shape[1]:
                y_left = np.min(np.where(closed[:, left] == 1))
                y_right = np.min(np.where(closed[:, right] == 1))
                x = [left, right]
                y = [y_left, y_right]
                x_new = np.linspace(left, right, num=(right - left + 1))
                y_smooth = make_interp_spline(x, y, k=1)(x_new)
                closed[np.round(y_smooth).astype(int), np.round(x_new).astype(int)] = 1

        #Updating blue mask with edge region
        blue_mask = red_mask.copy()
        blue_mask[:quarter_height, :] = closed

        #Filling columns with edge artifact
        for col in range(blue_mask.shape[1]):
            for row in range(blue_mask.shape[0]):
                if blue_mask[row, col] == 1:
                    blue_mask[row:, col] = 1
                    break

        #Removing noise and small artifacts
        for col in range(blue_mask.shape[1]):
            ones = np.where(blue_mask[:, col] == 1)[0]
            if len(ones) >= 25:
                blue_mask[ones[:25], col] = 0

        #Creating multi-class masks
        multi_mask = np.zeros_like(red_mask)
        multi_mask[(red_mask == 1) & (blue_mask == 1)] = 2
        multi_mask[(red_mask == 1) & (blue_mask == 0)] = 1

        #Correcting with neighborhood voting
        binary_mask = red_mask.copy()
        corrected_mask = multi_mask.copy()
        mask_to_fix = (binary_mask == 1) & (multi_mask == 0)
        indices = np.argwhere(mask_to_fix)
        padded_multi = np.pad(multi_mask, pad_width=1, mode='constant', constant_values=0)

        for i, j in indices:
            neighborhood = padded_multi[i:i+3, j:j+3].flatten()
            corrected_mask[i, j] = assign_label(neighborhood)

        #Applying geometric corrections
        corrected_mask = np.hstack([
            np.zeros((corrected_mask.shape[0], 1), dtype=np.uint8),
            corrected_mask[:, :-1]
        ])

        #Saving corrected multi-map .txt files
        out_txt_path = os.path.join(output_txt_dir, base_name + '.txt')
        np.savetxt(out_txt_path, corrected_mask, fmt='%d')

        #Generating and saving color-coded images
        colored = np.zeros((*corrected_mask.shape, 3), dtype=np.uint8)
        colored[corrected_mask == 1] = [0, 255, 0]   #Green
        colored[corrected_mask == 2] = [255, 0, 0]   #Red
        colored = np.hstack([
            np.zeros((colored.shape[0], 1, 3), dtype=np.uint8),
            colored[:, :-1, :]
        ])

        #Saving images as .png
        out_img_path = os.path.join(output_img_dir, base_name + '.png')
        Image.fromarray(colored).save(out_img_path)

        print(f"Processed and saved: {filename}")

print("All files processed and saved successfully!")