# -*- coding: utf-8 -*-
"""TIFF_Processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19prg_1fKK_jeFa0_Gk5whRQuOU3834RV

# **Code for Extracting B-Scans from 3D OCT Scans**
"""

#Installing tifffile library
!pip install -q tifffile ipywidgets

#Imports
from google.colab import drive
import os
import tifffile as tiff
import matplotlib.pyplot as plt
import ipywidgets as widgets
from IPython.display import display

#Mounting Google Drive
drive.mount('/content/drive')

#Definining OCT Viewer Class
class OCTViewer:
    def __init__(self, name, tiff_path, save_dir):
        self.name = name
        self.tiff_path = tiff_path
        self.save_dir = save_dir
        os.makedirs(save_dir, exist_ok=True)

        #Reading 3D OCT volume
        self.volume = tiff.imread(tiff_path)
        self.num_frames = self.volume.shape[0]
        print(f"[{self.name}] Shape: {self.volume.shape} | Saving frames...")

        self._save_frames()

    def _save_frames(self):
        for i in range(self.num_frames):
            path = os.path.join(self.save_dir, f"{self.name}_{i+1}.png")
            plt.imsave(path, self.volume[i], cmap='gray')
        print(f"[{self.name}]  Saved {self.num_frames} frames")

    def show_slider(self):
        def view(index):
            plt.figure(figsize=(5, 5))
            plt.imshow(self.volume[index], cmap='gray')
            plt.title(f"{self.name} | Frame {index+1}/{self.num_frames}")
            plt.axis('off')
            plt.show()
        return widgets.interactive(view, index=widgets.IntSlider(0, 0, self.num_frames - 1, description=self.name[:7]))

#List of datasets
datasets = [
    ("A-09_1", "/content/drive/MyDrive/Thesis/tiff/Timing_A-09_1_layer.tif", "/content/drive/MyDrive/Thesis/Saved_Frames_A-09_1"),
    ("A-09_2", "/content/drive/MyDrive/Thesis/tiff/Timing_A-09_2_layer.tif", "/content/drive/MyDrive/Thesis/Saved_Frames_A-09_2"),
    ("A-09_3", "/content/drive/MyDrive/Thesis/tiff/Timing_A-09_3_layer.tif", "/content/drive/MyDrive/Thesis/Saved_Frames_A-09_3"),
    ("T-16_1", "/content/drive/MyDrive/Thesis/tiff/Timing_T-16_1_layer.tif", "/content/drive/MyDrive/Thesis/Saved_Frames_T-16_1"),
    ("T-16_2", "/content/drive/MyDrive/Thesis/tiff/Timing_T-16_2_layer.tif", "/content/drive/MyDrive/Thesis/Saved_Frames_T-16_2"),
    ("T-16_3", "/content/drive/MyDrive/Thesis/tiff/Timing_T-16_3_layer.tif", "/content/drive/MyDrive/Thesis/Saved_Frames_T-16_3"),
    ("X5Y4_1", "/content/drive/MyDrive/Thesis/tiff/Timing_red_X5Y4_1_layer.tif", "/content/drive/MyDrive/Thesis/Saved_Frames_X5Y4_1"),
    ("X5Y4_2", "/content/drive/MyDrive/Thesis/tiff/Timing_red_X5Y4_2_layer.tif", "/content/drive/MyDrive/Thesis/Saved_Frames_X5Y4_2"),
    ("X5Y4_3", "/content/drive/MyDrive/Thesis/tiff/Timing_red_X5Y4_3_layer.tif", "/content/drive/MyDrive/Thesis/Saved_Frames_X5Y4_3"),
]

#Visualization
viewers = [OCTViewer(name, path, out) for name, path, out in datasets]
sliders = [v.show_slider() for v in viewers]
display(widgets.VBox(sliders))