# -*- coding: utf-8 -*-
"""Inference_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lqTzrwEup8KlusasvbSbSmjbwSmvZuYy

# **Inference Test**

**Mounting Google Drive**
"""

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

!pip install segmentation-models-pytorch

import os
import cv2
import time
import numpy as np
from glob import glob
import torch
import matplotlib.pyplot as plt
from tqdm import tqdm
import segmentation_models_pytorch as smp

#Setup
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
target_h, target_w = 256, 320

#Loading Models
unet_model = smp.Unet("resnet18", encoder_weights=None, in_channels=1, classes=3).to(device)
unet_model.load_state_dict(torch.load("/content/drive/MyDrive/Thesis/Weights_U-Net.pth", map_location=device))
unet_model.eval()

deeplab_model = smp.DeepLabV3Plus("resnet18", encoder_weights=None, in_channels=1, classes=3).to(device)
deeplab_model.load_state_dict(torch.load("/content/drive/MyDrive/Thesis/Weights_Deeplabv3+.pth", map_location=device))
deeplab_model.eval()

#Loading Test Images
test_images = sorted(glob("/content/drive/MyDrive/Thesis/Test/*.png"))

#Preprocessing
def preprocess_image(path):
    img = cv2.imread(path, cv2.IMREAD_GRAYSCALE).astype('float32') / 255.0
    img = cv2.resize(img, (target_w, target_h), interpolation=cv2.INTER_AREA)
    return torch.tensor(img).unsqueeze(0).unsqueeze(0).to(device)

with torch.no_grad():
    dummy = preprocess_image(test_images[0])
    for _ in range(10):
        _ = unet_model(dummy)
        _ = deeplab_model(dummy)

#Inference Timing
unet_times, deeplab_times = [], []
print("\n Running inference timing...")
for path in tqdm(test_images, desc=" Processing Test Images"):
    img = preprocess_image(path)
    with torch.no_grad():
        start = time.time(); _ = unet_model(img); unet_times.append(time.time() - start)
        start = time.time(); _ = deeplab_model(img); deeplab_times.append(time.time() - start)

#Report
avg_unet = np.mean(unet_times)
avg_deeplab = np.mean(deeplab_times)
print(f"\n U-Net Avg Time:     {avg_unet:.6f}s/image | FPS: {1/avg_unet:.2f}")
print(f" DeepLabV3+ Avg Time: {avg_deeplab:.6f}s/image | FPS: {1/avg_deeplab:.2f}")

#Overlay Visualization
#Decoding mask to RGB
def decode_segmentation_mask(mask, num_classes=3):
    colors = {0: [0, 0, 0], 1: [0, 255, 0], 2: [255, 0, 0]}
    h, w = mask.shape
    overlay = np.zeros((h, w, 3), dtype=np.uint8)
    for c in range(num_classes):
        overlay[mask == c] = colors[c]
    return overlay

#Choosing sample image
sample_img_path = test_images[1]
original_img = cv2.imread(sample_img_path, cv2.IMREAD_GRAYSCALE)
orig_h, orig_w = original_img.shape

#Predicting
image_tensor = preprocess_image(sample_img_path)
with torch.no_grad():
    pred_mask = torch.argmax(deeplab_model(image_tensor).squeeze(), dim=0).cpu().numpy()

#Resizing back to original resolution
pred_mask_resized = cv2.resize(pred_mask.astype(np.uint8), (orig_w, orig_h), interpolation=cv2.INTER_NEAREST)
overlay_mask = decode_segmentation_mask(pred_mask_resized)

#Overlay
image_rgb = cv2.cvtColor(original_img, cv2.COLOR_GRAY2RGB)
blended = cv2.addWeighted(image_rgb, 0.6, overlay_mask, 0.4, 0)

#Displaying
print(f" Original image size: {orig_w}×{orig_h}")
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.imshow(image_rgb)
plt.title("Original B-Scan")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(blended)
plt.title("Overlay: Prediction on Original Size")
plt.axis("off")
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

#Sample timing values
time_per_image = {
    "U-Net": avg_unet,
    "DeepLabV3+": avg_deeplab
}

#Converting to FPS
fps_values = {model: 1.0 / t for model, t in time_per_image.items()}

#Plotting Time per Image
plt.figure(figsize=(10, 4))
plt.subplot(1, 2, 1)
plt.bar(time_per_image.keys(), time_per_image.values(), color=['skyblue', 'orange'])
plt.ylabel("Time per Image (seconds)")
plt.title("Inference Time per Image")
plt.ylim(0, max(time_per_image.values()) * 1.2)
for i, val in enumerate(time_per_image.values()):
    plt.text(i, val + 0.0005, f"{val:.4f}s", ha='center')

#Plotting FPS
plt.subplot(1, 2, 2)
plt.bar(fps_values.keys(), fps_values.values(), color=['skyblue', 'orange'])
plt.ylabel("Frames Per Second (FPS)")
plt.title("Inference Speed (FPS)")
plt.ylim(0, max(fps_values.values()) * 1.2)
for i, val in enumerate(fps_values.values()):
    plt.text(i, val + 5, f"{val:.1f} FPS", ha='center')

plt.tight_layout()
plt.show()